### ISSUE TITLE
Support for pre-processor highlighting in style blocks?

### ISSUE THREAD

**Issue by danmindru** [JonathanWolfe/language-polymer#5]
Hi there,

First of all thanks for the extension, it's pretty awesome 🎉
I'm wondering, do you have any plans to support syntax highlighting for SCSS?  

Syntax highlighting seems to be inconsistent with nested and more complex [ampersand](https://jonsuh.com/blog/sass-bem-selector-and-trailing-ampersand#bem-selector-support) rules. Some examples:

| How it is  |  How I'd like it to be |
|------------|------------------------|
| ![style-scss](https://user-images.githubusercontent.com/1515742/36837500-dec60b5c-1d3c-11e8-9798-02b94a3b73cf.PNG) | ![style-scss-really](https://user-images.githubusercontent.com/1515742/36838356-47f516fc-1d3f-11e8-9d58-5f366eaae710.PNG) |

I've looked around and found an example done for [Vue.js](https://vuejs.github.io/vetur/highlighting.html) - the extension is [here](https://marketplace.visualstudio.com/items?itemName=octref.vetur). 

Let me know what you think. If you decide to support it, I could have a stab at it myself, however my knowledge regarding vscode extensions is limited 💩

**Comment by JonathanWolfe** [comment]
Thanks for the comments. I welcome you to give it a shot on your own, you should look at the below snippet for (probably) how to go about it: https://github.com/vuejs/vetur/blob/master/syntaxes/vue.json#L581-L602

We don't want to fix the styling because WE aren't the ones doing it, it's being parsed by the appropriate syntax file. And since `lang="scsss"` isn't a standard attribute, vscode doesn't identity the swap so we just need to tell it.

**Comment by danmindru** [comment]
Cool, thanks! I'll look into it then and see how far I can get.

**Comment by JonathanWolfe** [comment]
Closed via #7
